### ISSUE TITLE
Fix ASCII bug

### ISSUE THREAD

**Issue by sfbrunner** [sfbrunner/GraphSearch#29]
when searching "Noelia"

05/30/2018 09:31:51 PM [INFO]: Max degree: 5
[2018-05-30 21:31:51,763: INFO/MainProcess] Max degree: 5
[2018-05-30 21:31:51,763: WARNING/MainProcess] 9
[2018-05-30 21:31:51,763: WARNING/MainProcess] Traceback (most recent call last):
[2018-05-30 21:31:51,763: WARNING/MainProcess] File "/home/ubuntu/git/GraphSearch/backend/worker.py", line 23, in getGraph
[2018-05-30 21:31:51,764: WARNING/MainProcess] graphJSON = json.loads(graphSession.get_cy_json(graph_format=kwargs['graph_format'], mode=kwargs['mode']))
[2018-05-30 21:31:51,764: WARNING/MainProcess] File "/home/ubuntu/git/GraphSearch/backend/lib/GraphSession.py", line 52, in get_cy_json
[2018-05-30 21:31:51,765: WARNING/MainProcess] return resultGraph.get_graph(graph_format=graph_format)
[2018-05-30 21:31:51,765: WARNING/MainProcess] File "/home/ubuntu/git/GraphSearch/backend/lib/ResultGraph.py", line 60, in get_graph
[2018-05-30 21:31:51,766: WARNING/MainProcess] return self.get_cy_json()
[2018-05-30 21:31:51,766: WARNING/MainProcess] File "/home/ubuntu/git/GraphSearch/backend/lib/ResultGraph.py", line 82, in get_cy_json
[2018-05-30 21:31:51,766: WARNING/MainProcess] network_stats = self.get_search_stats(n_json)
[2018-05-30 21:31:51,766: WARNING/MainProcess] File "/home/ubuntu/git/GraphSearch/backend/lib/ResultGraph.py", line 165, in get_search_stats
[2018-05-30 21:31:51,766: WARNING/MainProcess] top_authors_list = ['{0} ({1})'.format(str(author[0]), str(author[1])) for author in top_authors]
[2018-05-30 21:31:51,767: WARNING/MainProcess] UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 3: ordinal not in range(128)

**Comment by sfbrunner** [comment]
Performed and referenced bugfix, merged into master, closing now.
